### ISSUE TITLE
dev-python/plum-py-0.8.5 fails with "packaging.specifiers.InvalidSpecifier: Invalid specifier: '>=3.6.*'"

### ISSUE THREAD

**Issue by u3shit** [houseofsuns/pypi#2]
Trying to emerge that package fails for me. 

```
  dist.fetch_build_eggs(dist.setup_requires)
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/plum-py-0.8.5/work/plum-py-0.8.5/setup.py", line 24, in <module>
    setup(
  File "/usr/lib/python3.11/site-packages/setuptools/__init__.py", line 103, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/distutils/core.py", line 121, in setup
    dist.parse_config_files()
  File "/usr/lib/python3.11/site-packages/setuptools/dist.py", line 623, in parse_config_files
    setupcfg.parse_configuration(
  File "/usr/lib/python3.11/site-packages/setuptools/config/setupcfg.py", line 177, in parse_configuration
    options.parse()
  File "/usr/lib/python3.11/site-packages/setuptools/config/setupcfg.py", line 500, in parse
    section_parser_method(section_options)
  File "/usr/lib/python3.11/site-packages/setuptools/config/setupcfg.py", line 475, in parse_section
    self[name] = value
    ~~~~^^^^^^
  File "/usr/lib/python3.11/site-packages/setuptools/config/setupcfg.py", line 293, in __setitem__
    parsed = self.parsers.get(option_name, lambda x: x)(value)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/packaging/specifiers.py", line 714, in __init__
    parsed.add(Specifier(specifier))
               ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/packaging/specifiers.py", line 245, in __init__
    raise InvalidSpecifier(f"Invalid specifier: '{spec}'")
packaging.specifiers.InvalidSpecifier: Invalid specifier: '>=3.6.*'
```

Full log: [build.log.txt](https://github.com/houseofsuns/pypi/files/13855632/build.log.txt)

**Comment by houseofsuns** [comment]
I'm unsure where the error is rooted and whether I can actually do something about it. At first glance this looks like an upstream problem.

...

Actually taking a look at [1] it seems that upstream fixed this but did not yet make a release.

[1] https://gitlab.com/dangass/plum/-/blob/master/setup.cfg?ref_type=heads

**Comment by houseofsuns** [comment]
Actually the two last releases do not provide source distfiles and thus the version in the overlay is 0.8.5 instead of 0.8.7. Sadly not a lot can be done if upstream does not provide sources.

**Comment by u3shit** [comment]
Well, at least you managed to find the source repository of this package, that's already better than what I could. :)
But interestingly, the old `>=3.6.*` specifier was added 3 years ago, many releases ago, so it's not like there were only one bad version. Or were there some backward icompatible change in python/setuptools/whatever?

**Comment by houseofsuns** [comment]
I opened an upstream issue here:
https://gitlab.com/dangass/plum/-/issues/151
